config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admins, path: 'admins', controllers: { admins: "admins/registrations" }
  devise_for :users, :controllers => { registrations: 'users/registrations' }

  get '/account/:id' => 'users#account', as: 'account'
  get '/pre-orders' => 'users#pre_orders', as: 'pre_orders'
  get '/nendoroids' => 'users#nendoroids', as: 'nendoroids'
  get '/in-stock'  => 'users#in_stock', as: 'in_stock'
  get '/request-nendo'  => 'users#request_nendo', as: 'request_nendo'
  get '/order-page'  => 'users#order_nendo', as: 'order_nendo'
  get '/nendoroid/:id' => 'users#view_nendo', as: 'view_nendo'

  get '/admins' => 'admins#index', as: 'dashboard'
  get '/all-transactions' => 'admins#all_transactions', as: 'all_transactions'
  get '/transaction-status' => 'admins#transaction_status', as: 'transaction_status'
  get '/orders' => 'admins#orders', as: 'orders'
  post '/upload-nendo' => 'admins#create', as: 'upload_nendo'
  get '/availability-status' => 'admins#availability_status', as: 'availability_status'

  post '/create_order' => 'orders#create', as: 'create_order'

  get "/", to: "users#index", :as => :user_root
  get "/admins", to: "admins#index", :as => :admin_root

  resources :admins
  resources :users
  resources :orders
end

app/views/admins/availability_status.html.erb
<div class="body-container">   
    <div class="back-container">
        <%= link_to "◄ Back", "/admins" %>
    </div>
    <h1 id="pending-h1">Availability Status</h1>

    <table id="customers">
    <tr>
        <th>Nendoroid Number</th>
        <th>Nendoroid Name</th>
        <th>Current Status</th>
        <th>New Status</th>
        <th>Action</th>
    </tr>
    <% @nendos.each do |n|%>
    <tr>
        <td><%= n.nendoroid_number %></td>
        <td><%= n.name %></td>
        <% if n.availability == false %>
            <td><strong>Not Available</strong></td>
        <% else %>
            <td><strong>Available</strong></td>
        <% end %>
        <%= form_with scope: :nendoroid, url: admin_path(n), method: "patch" do |f| %>
            <td><%= f.select(:availability, [['Available', 'true'], ['Not Available', 'false']]) %></td>
      
            <td><%= f.submit "Update" %></td>
        <% end %>
    </tr>
    <% end %>
    </table>
</div>

app/views/admins/index.html.erb
<div class="body-container">  
  <h1 id="admin-users-h1">Users</h1>
  <table id="customers">
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Action</th>
    </tr>
    <% @users.each do |user| %>
    <tr>
      <td><strong><%= user.name %></strong></td>
      <td><strong><%= user.email %></td>
      <td><strong><a href="<%= admin_path(user) %>">View User</a></td>
    </tr>
    <% end %>
  </table>
</div>

app/views/admins/new.html.erb
<div class="body-container">   
  <div class="back-container">
      <%= link_to "◄ Back", "/admins" %>
    </div>
  <h1 id="pending-h1">Upload Nendoroid</h1>

  <%= form_with scope: :nendoroid, url: upload_nendo_path do |f| %>
    
    <div class="field">
      <%= f.label :name,"Name: " %>
      <%= f.text_field :name %>
    </div>
    
    <div class="field">
      <%= f.label :nendoroid_number,"Nendoroid Number: " %>
      <%= f.number_field :nendoroid_number %>
    </div>

    <div class="field">
      <%= f.label :series,"Series: " %>
      <%= f.text_field :series %>
    </div>

    <div class="field">
      <%= f.label :simple_description,"Tagline: " %>
      <%= f.text_field :simple_description %>
    </div>

    <div class="field">
      <%= f.label :description,"Description: " %>
      <%= f.text_area :description %>
    </div>

    <div class="field">
      <%= f.label :price,"Price: " %>
      <%= f.number_field :price %>
    </div>

    <div class="field">
      <%= f.label :release_date,"Release Date: " %>
      <%= f.date_field :release_date %>
    </div>

    <div class="field">
      <%= f.label :pre_order_price,"Pre-Order: " %>
      <%= f.number_field :pre_order_price %>
    </div>

    <div class="field">
      <%= f.label :pre_order_date,"Pre-Order Date: " %>
      <%= f.date_field :pre_order_date %>
    </div>

    <div class="field">
      <%= f.label :eta,"ETA: " %>
      <%= f.date_field :eta %>
    </div>

    <div class="field">
      <%= f.label :min_deposit,"Minimal Deposit: " %>
      <%= f.number_field :min_deposit %>
    </div>

    <div class="field">
      <%= f.label(:availability, "Availability:") %>
      <%= f.check_box(:availability) %>
    </div>

    <div class="field">
      <%= f.label :main_photo,"Main Photo: " %>
      <%= f.file_field :main_photo %>
    </div>

    <div class="field">
      <%= f.label :photos,"Other Photos: " %>
      <%= f.file_field :photos, multiple: true %>
    </div>

    <div class="actions">
      <%= f.submit "Upload" %>
    </div>
  <% end %>
</div>  

app/views/admins/orders.html.erb
<div class="body-container">   
  <div class="back-container">
    <%= link_to "◄ Back", "/admins" %>
  </div>
  <h1 id="pending-h1">Orders</h1>

  <table id="customers">
    <tr>
      <th>Order Number</th>
      <th>Item</th>
      <th>Price</th>
      <th>Order made by</th>
      <th>Status</th>
      <th>Date of Transaction</th>
    </tr>
    <% @orders.each do |o|%>
    <tr>
      <td><%= o.id %></td>
      <td><%= o.nendoroid_name %></td>
      <td><%= o.total_price %></td>
      <% @users.each do |u|%>
        <%if u.id == o.user_id%>
          <td><%= u.name %></td>
        <% end %>
      <% end %>
      <td><%= o.status %></td>
      <td><%= o.created_at %></td>
    </tr>
    <% end %>
  </table>
</div>

app/views/admins/show.html.erb
<div class="body-container">  
    <div class="user-info-container">
        <div class="back-container">
            <%= link_to "◄ Back", "/admins" %>
        </div>
        <h1>User Info</h1>

        <h3> Personal Information </h3>
        <hr class="solid">    

        <div class="user-info-item">
            <label>Name:</label>
            <p class="user-infomation"><%= @user.name %></p>
        </div>
        <div class="user-info-item">
            <label>Phone Number:</label>
            <p class="user-infomation"><%= @user.phone_number %></p>
        </div>
        <div class="user-info-item">
            <label>Email:</label>
            <p class="user-infomation"><%= @user.email %></p>
        </div>
        <div class="edit-user-div">
            <%# <%= link_to "Edit User", edit_admin_path(@user.id) %>
        </div>


        
    <h3> <%= @user.name %>'s Orders</h3>
    <hr class="solid">

    <table id="customers">
        <tr>
        <th>Order Number</th>
        <th>Item</th>
        <th>Price</th>
        <th>Status</th>
        </tr>
        <% @user_orders.each do |uo|%>
        <tr>
        <td><%= uo.id %></td>
        <td><%= uo.nendoroid_name %></td>
        <td><%= uo.total_price %></td>
        <td><%= uo.status %></td>
        </tr>
        <% end %>
    </table>
        
    </div>
</div>

app/views/admins/transaction_status.html.erb
 <div class="body-container">   
  <div class="back-container">
      <%= link_to "◄ Back", "/admins" %>
    </div>
  <h1 id="pending-h1">Transaction Status</h1>

  <table id="customers">
    <tr>
      <th>Order Number</th>
      <th>Item</th>
      <th>Price</th>
      <th>Order made by</th>
      <th>Status</th>
      <th>New Status</th>
      <th>Action</th>
    </tr>
    <% @orders.each do |o|%>
    <tr>
      <td><%= o.id %></td>
      <td><%= o.nendoroid_name %></td>
      <td><%= o.total_price %></td>
      <% @users.each do |u|%>
        <%if u.id == o.user_id%>
          <td><%= u.name %></td>
        <% end %>
      <% end %>
      <td><%= o.status %></td>
      <%= form_with model: @order, url: order_path(o), method: "patch" do |f| %>
      <td><%= f.select(:status, [['Paid', 'Paid'], ['Canceled', 'Canceled']]) %></td>
      
      <td><%= f.submit "Update" %></td>
      <% end %>
    </tr>
    <% end %>
  </table>
</div>