config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admins, path: 'admins', controllers: { admins: "admins/registrations" }
  devise_for :users, :controllers => { registrations: 'users/registrations' }

  get '/account/:id' => 'users#account', as: 'account'
  get '/pre-orders' => 'users#pre_orders', as: 'pre_orders'
  get '/nendoroids' => 'users#nendoroids', as: 'nendoroids'
  get '/in-stock'  => 'users#in_stock', as: 'in_stock'
  get '/request-nendo'  => 'users#request_nendo', as: 'request_nendo'
  get '/order-page'  => 'users#order_nendo', as: 'order_nendo'
  get '/nendoroid/:id' => 'users#view_nendo', as: 'view_nendo'

  get '/admins' => 'admins#index', as: 'dashboard'
  get '/all-transactions' => 'admins#all_transactions', as: 'all_transactions'
  get '/transaction-status' => 'admins#transaction_status', as: 'transaction_status'
  get '/orders' => 'admins#orders', as: 'orders'
  post '/upload-nendo' => 'admins#create', as: 'upload_nendo'
  get '/availability-status' => 'admins#availability_status', as: 'availability_status'

  post '/create_order' => 'orders#create', as: 'create_order'

  get "/", to: "users#index", :as => :user_root
  get "/admins", to: "admins#index", :as => :admin_root

  resources :admins
  resources :users
  resources :orders
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  validates :email, presence: true
  validates :password, presence: true
  validates :phone_number, presence: true
  validates :address, presence: true
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :phone_number, :address])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!, only:[:show, :edit, :pre_orders, :in_stock, :order_nendo, :account]
  def index
    client = Twitter::REST::Client.new do |config|
      config.consumer_key        = Rails.application.credentials.twitter[:consumer_key]
      config.consumer_secret     = Rails.application.credentials.twitter[:consumer_secret]
      config.access_token        = Rails.application.credentials.twitter[:access_token]
      config.access_token_secret = Rails.application.credentials.twitter[:access_token_secret]
    end

    @twitter_feed = client.user_timeline("GoodSmile_US")
  end

  def show
    @user = User.find(params[:id])
  end
  
  def edit
    @user = User.find(params[:id])
  end

  def nendoroids
    @nendos = Nendoroid.all.order(nendoroid_number: :desc)
  end

  def pre_orders
    @pre_orders = Nendoroid.where('release_date > ?', Time.now)
  end

  def in_stock
    @in_stock = Nendoroid.where(availability: true)
  end

  def view_nendo
    @nendo = Nendoroid.find(params[:id])
  end

  def order_nendo
    @nendo = Nendoroid.find(params[:id])
  end
    
  def account
    @user = current_user
    @user_orders = Order.where('user_id =?', @user.id).order(id: :asc)
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :phone_number, :balance, :address)
  end
end

app/views/users/account.html.erb
<div class="body-container">
  <div class="back-container">
      <%= link_to "◄ Back", "/" %>
  </div>

  <h1>My account</h1>

  <h3> Personal Information </h3>
  <hr class="solid">

  <div class="account-container">

    <label>Name:</label>
    <input type="text" value='<%= current_user.name %>' disabled>

    <label>Phone Number:</label>
    <input type="text" value='<%= current_user.phone_number %>' disabled>

    <label>Address:</label>
    <input type="text" value='<%= current_user.address %>' disabled>

    <label>Email:</label>
    <input type="text" value='<%= current_user.email %>' disabled>

    
  </div>

  <h3> Your Orders</h3>
  <hr class="solid">

  <table id="customers">
    <tr>
      <th>Order Number</th>
      <th>Item</th>
      <th>Price</th>
      <th>Status</th>
    </tr>
    <% @user_orders.each do |uo|%>
    <tr>
      <td><%= uo.id %></td>
      <td><%= uo.nendoroid_name %></td>
      <td><%= uo.total_price %></td>
      <td><%= uo.status %></td>
    </tr>
    <% end %>
  </table>
</div>

app/views/users/in_stock.html.erb
<div class="body-container">

  <div class="back-container">
    <%= link_to "◄ Back", "/" %>
  </div>
  
  <h1 id="pending-h1">In-Stock</h1>

  <div class="nendoroid-container">
    <% @in_stock.each do |nendo| %>
      <div class="nendoroid-item-container">
        <%= image_tag nendo.main_photo, class: "nendoroid-photo"%>
        <div class="nendoroid-item-info-container">
          <div class="vl"></div>
          <span>Nendoroid <%= nendo.nendoroid_number %><span><br>
          <span><%= nendo.name %><span>
          <%= button_to "🛒 Order this!", order_nendo_path, params: {:id => nendo.id}, method: :get %>
        </div>
      </div>
    <% end %>
  </div>

</div>

app/views/users/index.html.erb
<div class="body-container">
  <h1>Welcome to OnegaiOniichan Toy Store!</h1>
  <%= image_tag("logo.png", class: "main-logo") %>
  <%= link_to image_tag("shop_now.png", class: "shop-image"), in_stock_path %>


  <div class="twitter-feed-container">
    <h2 class="twitter-feed-container-title">Updates from GoodSmile US:</h2>
    <% @twitter_feed.each do |tweet| %>
      <div class="twitter-container">
        <div class="twitter-header">
          <%= image_tag("gsc_logo.jpg", class: "twitter-account-logo") %>
          <p>GoodSmile_US</p>
          <%= image_tag("verified.png", class: "twitter-verified-logo") %>
          <p><a href="https://twitter.com/GoodSmile_US">@GoodSmile_US</a></p>
        </div>
        <div class="twitter-body">
          <% string = tweet.text %>
          <% splitStr = string.split(" ") %>
          <% link = splitStr[-1] %>
          <% splitStr.delete(link) %>
          <p><%= splitStr.join(" ") %></p>
          <a href="<%= link %>"><%= link %></a>
        </div>
      </div>
    <% end %>
  </div>

</div>

app/views/users/nendoroids.html.erb
<div class="body-container">
  <div class="back-container">
    <%= link_to "◄ Back", "/" %>
  </div>
  <h1>What is a Nendoroid?</h1>
  <div class="nendo-intro-container">
    <%= image_tag("nendoroid_photo.png", class: "nendoroid-series") %>
    <p class="nendo-intro"><strong>Nendoroid (ねんどろいど nendoroido) series </strong>is a brand of plastic figures created by the Japanese Company Good Smile Company. They typically depict characters from anime, manga, or video games and are designed with a large head and smaller body to give them a cute apperance. Their faces and other body parts are exchangeable, giving them a range of different expressions and poses. The Nendoroid brand spans a variety of different products: the original 10 cm figures, smaller Nendoroid Petite figures, additional display tools known as the Nendoroid More series as well as plushes and play sets. Several video games have also been released based on Nendoroid designs.</p>
  </div>

  <h1>Nendoroids</h1>
  <div class="nendoroid-container">
    <% @nendos.each do |nendo| %>
      <%= link_to view_nendo_path(nendo) do %>
        <div class="nendoroid-item-container">
          <%= image_tag nendo.main_photo, class: "nendoroid-photo"%>
          <% if Time.now < nendo.release_date %>
            <strong class="availability">Pre-Order Now!</strong>
          <% elsif Time.now > nendo.release_date && nendo.availability == true %>
            <strong class="availability">Order Now!</strong>
          <% else %>
            <strong class="availability">Not Available!</strong>
          <% end %>
          <div class="nendoroid-item-info-container">
            <div class="vl"></div>
            <span>Nendoroid <%= nendo.nendoroid_number %><span><br>
            <span><%= nendo.name %><span>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>

</div>

app/views/users/order_nendo.html.erb
<div class="body-container">
  <div class="back-container">
    <%= link_to "◄ Back", "/" %>
  </div>
  <h1 id="pending-h1">Your Order:</h1>

  <table id="customers">
    <tr>
      <th>Item</th>
      <th>Price</th>
    </tr>
    <tr>
      <td><%= @nendo.name %></td>
      <td><%= @nendo.price %></td>
    </tr>
  </table>

  <%= button_to "Place Order", create_order_path,
      params: {:nendoroid_id => @nendo.id, :nendoroid_name => @nendo.name, :total_price => @nendo.price, :user_id => current_user.id},
      method: :post %>
</div>

app/views/users/pre_orders.html.erb
<div class="body-container">

  <div class="back-container">
    <%= link_to "◄ Back", "/" %>
  </div>

  <h1 id="pending-h1">Pre-Orders</h1>

  <div class="nendoroid-container">
    <% @pre_orders.each do |nendo| %>
      <div class="nendoroid-item-container">
        <%= image_tag nendo.main_photo, class: "nendoroid-photo"%>
        <div class="nendoroid-item-info-container">
          <div class="vl"></div>
          <span>Nendoroid <%= nendo.nendoroid_number %><span><br>
          <span><%= nendo.name %><span>
          <%= button_to "🛒 Pre-Order this!", order_nendo_path, params: {:id => nendo.id}, method: :get %>
        </div>
      </div>
    <% end %>
  </div>

</div>

app/views/users/request_nendo.html.erb
<div class="body-container">  
  <div class="back-container">
    <%= link_to "◄ Back", "/" %>
  </div>
  <h1 id="pending-h1">Request a Nendoroid</h1>

</div>

app/views/users/show.html.erb
<h1>My account</h1>

<ul>
  <% @user.each do |u| %>
    <li>
      <%= u.name %>
      <%= u.phone_number %>
      <%= u.address %>
      <%= u.email %>
      <%= u.balance %>
    </li>
  <% end %>
</ul>

app/views/users/view_nendo.html.erb
<div class="body-container">
    <div class="back-container">
        <%= link_to "◄ Back", "/nendoroids" %>
    </div>
    <div class="view_nendo-container">
        <div class="nendo_details-container">
            <h3>Release Date: <%= @nendo.release_date %></h3>
            <h3>Nendoroid <%= @nendo.nendoroid_number %></h3>
            <h1 id="pending-h1"><%= @nendo.name %></h1>

            <h4><%= @nendo.simple_description %></h4>
            <p><%= @nendo.description %></p>

            <hr class="solid">

            <h3 class='pd-header'>Product details</h3>

            <p><strong>Product Name: </strong> <%= @nendo.name %></p>
            <p><strong>Series: </strong> <%= @nendo.series %></p>
            <p><strong>Release Date: </strong> <%= @nendo.release_date %></p>
            <p><strong>Pre-order starts at </strong><%= @nendo.release_date %></p>
            <p><strong>ETA: </strong> <%= @nendo.eta %></p>
            <p><strong>Price: </strong>Php <%= @nendo.price %>0</p>
            <p><strong>Pre-order Price: </strong>Php <%= @nendo.pre_order_price %>0</p>
            <p><strong>Minimum Deposit: </strong>Php <%= @nendo.min_deposit %>0</p>
        </div>

        <div class="nendo_photos-container">
            <% @nendo.photos.each do |np| %>
                <% if np.variable? %>
                    <%= image_tag np %>
                <% end %>
            <% end %>
        </div>
    </div>
</div>