config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admins, path: 'admins', controllers: { admins: "admins/registrations" }
  devise_for :users, :controllers => { registrations: 'users/registrations' }

  get '/account/:id' => 'users#account', as: 'account'
  get '/pre-orders' => 'users#pre_orders', as: 'pre_orders'
  get '/nendoroids' => 'users#nendoroids', as: 'nendoroids'
  get '/in-stock'  => 'users#in_stock', as: 'in_stock'
  get '/request-nendo'  => 'users#request_nendo', as: 'request_nendo'
  get '/order-page'  => 'users#order_nendo', as: 'order_nendo'
  get '/nendoroid/:id' => 'users#view_nendo', as: 'view_nendo'

  get '/admins' => 'admins#index', as: 'dashboard'
  get '/all-transactions' => 'admins#all_transactions', as: 'all_transactions'
  get '/transaction-status' => 'admins#transaction_status', as: 'transaction_status'
  get '/orders' => 'admins#orders', as: 'orders'
  post '/upload-nendo' => 'admins#create', as: 'upload_nendo'
  get '/availability-status' => 'admins#availability_status', as: 'availability_status'

  post '/create_order' => 'orders#create', as: 'create_order'

  get "/", to: "users#index", :as => :user_root
  get "/admins", to: "admins#index", :as => :admin_root

  resources :admins
  resources :users
  resources :orders
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :line_items, dependent: :destroy
    has_many :nendoroid, through: :line_items

    def sub_total
        sum = 0
        self.line_items.each do |line_item|
          sum+= line_item.total_price
        end
        return sum
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @cart = @current_cart
  end

  def destroy
    @cart = @current_cart
    @cart.destroy
    session[:cart_id] = nil
    redirect_to "/"
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/show.html.erb
<h2>Cart show</h2>
<ul>
  <% @cart.line_items.each do |line_item| %>
    <li>Item: <%= line_item.nendoroid.name %>/ Price: <%= number_to_currency(line_item.nendoroid.price) %>/ Quantity: <%= line_item.quantity %>/ Total Price: <%= number_to_currency(line_item.total_price) %>
    # See lineItem section below for explanation of line_item links
    <ul>
      <li>
        <%= link_to "Add one", line_item_add_path(:id => line_item), method: :post %>
        <%= link_to "Reduce one", line_item_reduce_path(:id => line_item), method: :post %>
      </li>
      <li>
        <%= link_to "Remove item", line_item_path(line_item), method: :delete %>
      </li>
    </ul>
    #
  <% end %>
</ul>
<h3>Sub total: <%= number_to_currency(@cart.sub_total) %></h3>

<%= link_to "Proceed to checkout", new_order_path %><br>

<%= link_to "Empty cart", cart_path(@current_cart), method: :delete, data: {confirm: "Are you sure?"} %>