config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admins, path: 'admins', controllers: { admins: "admins/registrations" }
  devise_for :users, :controllers => { registrations: 'users/registrations' }

  get '/account/:id' => 'users#account', as: 'account'
  get '/pre-orders' => 'users#pre_orders', as: 'pre_orders'
  get '/nendoroids' => 'users#nendoroids', as: 'nendoroids'
  get '/in-stock'  => 'users#in_stock', as: 'in_stock'
  get '/request-nendo'  => 'users#request_nendo', as: 'request_nendo'
  get '/order-page'  => 'users#order_nendo', as: 'order_nendo'
  get '/nendoroid/:id' => 'users#view_nendo', as: 'view_nendo'

  get '/admins' => 'admins#index', as: 'dashboard'
  get '/all-transactions' => 'admins#all_transactions', as: 'all_transactions'
  get '/transaction-status' => 'admins#transaction_status', as: 'transaction_status'
  get '/orders' => 'admins#orders', as: 'orders'
  post '/upload-nendo' => 'admins#create', as: 'upload_nendo'
  get '/availability-status' => 'admins#availability_status', as: 'availability_status'

  post '/create_order' => 'orders#create', as: 'create_order'

  get "/", to: "users#index", :as => :user_root
  get "/admins", to: "admins#index", :as => :admin_root

  resources :admins
  resources :users
  resources :orders
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OnegaiOniichan</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag 'logo.png' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>
  <body>

  <!--           Nav bar               -->
    <div class="topnav" id="myTopnav">
      <%= link_to '<i class="fa fa-child"></i> Nendoroids'.html_safe, nendoroids_url %>
      
      <% if user_signed_in? %>
          
        <%= link_to '<i class="fa fa-archive"></i> Pre-Orders'.html_safe, pre_orders_url %>
        
        <%= link_to '<i class="fa fa-shopping-cart"></i> In-stock'.html_safe, in_stock_url %>
        
        <%= link_to '<i class="fa fa-user-circle"></i> Account'.html_safe, account_url(current_user) %>
        
        <%= link_to '<i class="fa fa-sign-out"></i> Logout'.html_safe, destroy_user_session_path(), method: :delete %>
      <% end %>
      <% unless user_signed_in? || admin_signed_in?%>
        <%= link_to '<i class="fa fa-sign-in"></i> Login'.html_safe, new_user_session_path() %>
        <%= link_to '<i class="fa fa-user-plus"></i> Register'.html_safe, new_user_registration_path() %>
      <% end %>
      <% if admin_signed_in? %>
        <%= link_to '<i class="fa fa-clipboard"></i> Orders'.html_safe, orders_url %>
       
        <%= link_to '<i class="fa fa-list-alt"></i> Availability Status'.html_safe, availability_status_path, data: { turbolinks: false } %>
        
        <%= link_to '<i class="fa fa-credit-card-alt"></i> Transaction Status'.html_safe, transaction_status_url, data: { turbolinks: false } %>
        
        <%= link_to '<i class="fa fa-upload"></i> Upload Nendo'.html_safe, new_admin_path %>
        
        <%= link_to '<i class="fa fa-sign-out"></i> Logout'.html_safe, destroy_admin_session_path(), method: :delete %>
      <% end %>
      <a href="javascript:void(0);" class="icon" onclick="myFunction()">
        <i class="fa fa-bars"></i>
      </a>
    </div>
  

  <!--           yield              -->
    <div class="yield-container">
      <% if flash[:notice] %>
        <p class="notice" id="notice-id"><%= notice %></p>
      <% end %>
      <% if flash[:alert] %>
        <p class="alert" id="alert-id"><%= alert %></p>
      <% end %>
      <%= yield %>
     
    </div>

    <!-- Script -->
    <script>
      function myFunction() {
        var x = document.getElementById("myTopnav");
        if (x.className === "topnav") {
          x.className += " responsive";
        } else {
          x.className = "topnav";
        }
      }
    </script>

    <footer class="footer">
      <div class="footer-text">
        <p class="footer-p">© Copyright 2021 OnegaiOniichan Store</p>
        <p class="footer-p">Powered by Ruby on Rails</p>
      </div>  
    </footer>
  </body>
</html>